FROM grafana/alloy:latest
COPY config.alloy /etc/alloy/config.alloy
CMD ["run", "--server.http.listen-addr=0.0.0.0:12345", \
     "--stability.level=public-preview", \
     "--storage.path=/var/lib/alloy/data", \
     "/etc/alloy/config.alloy"]
